### ISSUE TITLE
Fix selected country icon in All Cities chart

### ISSUE THREAD

**Issue by themightybruce** [free-radicals/AirPollution#103]
- Selected City text and circle should disappear whenever the regional boxes are clicked or hovered over (otherwise it is not clear the different between the country points and the regional points of the same color

- unbold Selected Country
- remove black line around selected country, and change to match chart (looks like a grey stroke)

**Comment by dominickp** [comment]
Complete in cb1c117d0d66a8fd63ce9a464d1c7b9f7d7e4836
