### ISSUE TITLE
Add data coverage warning when selecting city

### ISSUE THREAD

**Issue by themightybruce** [free-radicals/AirPollution#106]
When I cleaned the WHO city data I included a column with a warning text for any city which had a data coverage of lower than 75%.

If the user picks one of these cities an alert (sweet alert) should pop up and display the warning contained in the csc column:

_This station has low data coverage (<75%), therefore the annual mean pollution level may not be an accurate representation of the annual conditions.  Caution is advised when interpreting this result._  

Maybe we also change station to city.

This one is important from a data integrity point of view and gives us some coverage in case someone comes back and questions the data validity (which they would be entitled to do for certain cities).

**Comment by dominickp** [comment]
Complete in fd13d55dcb11e863f92e2b96a15426bcff526526
