### ISSUE TITLE
Act 3: Change color of points on globe to match the regional colors in the All Cities chart

### ISSUE THREAD

**Issue by themightybruce** [free-radicals/AirPollution#108]
We could have them colored on load, or perhaps on hover?

**Comment by dominickp** [comment]
Unfortunately, we'd have to redo our coordinates.csv dataset to include the region to make this happen. We may want to pass on this one.

**Comment by dominickp** [comment]
Complete in 9d239efe706349ff47bfb2835b0278efd2f8cd0a
