### ISSUE TITLE
When clicking back to the vis from the process book we should remember the user city selection and enable full scrolling

### ISSUE THREAD

**Issue by themightybruce** [free-radicals/AirPollution#110]
Is a bit of a hassle to go back and have to reenter the city if you have visited the process book.

**Comment by dominickp** [comment]
Complete in b47624ae2bd580a7435b96b9ef011fee789ee4f9

- City is now stored in localStorage (similar to a browser cookie)
- If the city is found in localStorage, it will skip the intro and city selection and bounce the user to All Cities

**Comment by themightybruce** [comment]
This update is causing some buggy behavior.  When you return from the process book to the All Cities chart, we see the force layout bouncing the numbers about.  Also, when refreshing after a city selection is made then the page briefly shows the All Cities chart.

Perhaps if we take the user back to the countries over time chart, instead of the All Cities chart,  that would help?

**Comment by mariusdv** [comment]
I think that this feature breaks more than it gains. 
When going back, I think the selected city should be set (so you do not have to search for it again), but other than that you should just go back to the beginning of the page. (the same as shareable links)

**Comment by themightybruce** [comment]
Agreed Marius
