### ISSUE TITLE
Tooltip y separation issue for PM2.5 over time chart

### ISSUE THREAD

**Issue by themightybruce** [free-radicals/AirPollution#17]

**Comment by dominickp** [comment]
Could you include a screenshot?

**Comment by dominickp** [comment]
@themightybruce Still unclear on this one!

**Comment by dominickp** [comment]
All Cities chart move tooltip up a few pixels

**Comment by dominickp** [comment]
Complete in 1b8ec200f390c920c38b4e47039d188d37d712cb
