### ISSUE TITLE
Act 1 Air chart (horizontal bar)

### ISSUE THREAD

**Issue by themightybruce** [free-radicals/AirPollution#26]
- Move vertical line chart to not overwhelm reader
- Move axis to top

**Comment by dominickp** [comment]
Where do you think the vertical line chart should be moved to? Do you mean just keep it in its own section?

**Comment by dominickp** [comment]
Axis moved to top in bff738b237d5f5b652220c6d23207f87fc640f31

**Comment by dominickp** [comment]
Move gauge line chart under current all cities chart
