### ISSUE TITLE
Act 3: Action think about redesign

### ISSUE THREAD

**Issue by themightybruce** [free-radicals/AirPollution#32]
ideas:
- start with single city point
- animate addition of all other cities in dataset, to show interconnections/mesh
- then blend land/sea at the end.

**Comment by mariusdv** [comment]
could be done, if all cities get lat-lon data as dataset.
If these are not added as dataset, loading time would be way to long.

**Comment by dominickp** [comment]
@mariusdv It seems like this one may be somewhat complete apart from blending. Could you update this?

**Comment by dominickp** [comment]
See #91
