### ISSUE TITLE
Vis 1 changes

### ISSUE THREAD

**Issue by dominickp** [free-radicals/AirPollution#49]
- Try label at 90 degrees
- Make other city lines grey
- Make safe level black

**Comment by dominickp** [comment]
- change starting cities to include Dehli

**Comment by dominickp** [comment]
@themightybruce What city should I add? I thought you said New Dehli on today's call but I don't see it in the dataset.

**Comment by mariusdv** [comment]
@dominickp, "Delhi, India" & "Beijing, China".
~ I do notice that when you choose delhi, no new line shows up

**Comment by dominickp** [comment]
@mariusdv I guess I'm confused about the issue then because I don't see Dehli in the city selector and I assume its also not in the dataset. Where are you seeing Dehli as an option?

**Comment by mariusdv** [comment]
![schermafdruk 2016-04-21 19 30 12](https://cloud.githubusercontent.com/assets/12096742/14718519/791cd79c-07f7-11e6-8f1e-98773395e5f8.png)

**Comment by mariusdv** [comment]
delhi information works?

**Comment by dominickp** [comment]
Oh wow, I was spelling it wrong.... I'll take care of adding it to the vis 1 graphic on load.

**Comment by dominickp** [comment]
Complete in d3e98a271ff3494d5cb22b29def5469981f7c7a8
