### ISSUE TITLE
Intro section blocks look

### ISSUE THREAD

**Issue by mariusdv** [free-radicals/AirPollution#55]
- In the intro section, increase the font of the 3 blocks. For each block, think of more accurate icons to fit the narrative. I would include icons of people to hit the message home to the heart. For example, for the heart with the cross, you can show a hospital patient in a hospital bed - just a thought

**Comment by dominickp** [comment]
Closing for now. Re-open if you think it still needs work.

**Comment by mariusdv** [comment]
because of issue #27 , I think that adding images in those panels could be a nice addition. 
(Just an idea)
