### ISSUE TITLE
processbook needs to be up-to-date. All TO-DO's resolved

### ISSUE THREAD

**Issue by mariusdv** [free-radicals/AirPollution#63]

**Comment by dominickp** [comment]
I'm confused about this one. Could you be a little more specific?

**Comment by mariusdv** [comment]
The processbook has to be complete before prototype V2.

There are still some 'Todo' Items inside the processbook text. These need to be replaced with actual text. We also have to write about all changes we made in the visualization design.

**Comment by mariusdv** [comment]
split up into different issues
