### ISSUE TITLE
Add "About authors" to the end of the page

### ISSUE THREAD

**Issue by mariusdv** [free-radicals/AirPollution#77]

**Comment by dominickp** [comment]
What are you referring to? "The Free Radicals" section on the process book?

**Comment by mariusdv** [comment]
Commenting on my phone, so no Idea if this will work properly. 

Maybe having something similar to that part of the process book, or just our names somewhere on the main page. 

This could go underneath act 3 or at the top of the page. You can see it on quite a few sites like the telegraph, who, nyt,...

This was an idea I had while browsing random news sites. 
I don't mind having the issue closed if you think it's enough that our names are found in the processbook.

**Comment by dominickp** [comment]
Maybe we should have a nice graphical footer section which has this stuff and also includes the sharing icons. I'll give it some thought.

**Comment by dominickp** [comment]
@mariusdv instead of having our names and pictures in two places, why don't we link to the process book from the bottom of the footer, after the sharing icons. Like "check out how we built this site" and it goes to the process book. Would that be an acceptable solution to this issue?

**Comment by dominickp** [comment]
Per discussion: perhaps just add author names somewhere up top

**Comment by dominickp** [comment]
@themightybruce already took care of this one
