### ISSUE TITLE
Place social media share buttons in their own bar

### ISSUE THREAD

**Issue by mariusdv** [free-radicals/AirPollution#78]

**Comment by dominickp** [comment]
Where should the bar go? It should stay in the last section, right? We could move it to the header too.

**Comment by mariusdv** [comment]
I like it at the last section. 

Having it at the top of the page could also work, because you'll have to click through the entire page just to share it right now. 

(we could also do both, like small share buttons in the header and the bigger ones in act 3).

This issue is more of a brainstorm and asking for your guys feedback & opinions about the button placement, than an actual issue.

**Comment by dominickp** [comment]
Let me know your thoughts on this: 70ce19d9e5436aee2d1d4a0d16446e9c27551b5b
