### ISSUE TITLE
timeline text for Beijing and Delhi do not appear on iPad

### ISSUE THREAD

**Issue by themightybruce** [free-radicals/AirPollution#81]
Plus a host of other issues on mobile.  

We may not have time to fix these issues, if not we should add a message saying something like "this site is best viewed on a desktop screen."

**Comment by mariusdv** [comment]
I think we could easily add the "Please View on Desktop" .
There are also a few issues with Microsoft Edge.

Firefox and Chrome work fine.

**Comment by dominickp** [comment]
Simply alert of non-working browsers

**Comment by dominickp** [comment]
@mariusdv already took care of this one.
