### ISSUE TITLE
Scatter-plot improvements

### ISSUE THREAD

**Issue by dominickp** [free-radicals/AirPollution#86]
Per Alain's feedback:

> - Scatterplot - Similar to the line graph, once the user has clicked on it, you want to permanently hide the hand icon. FYI... there are orange circles that are highlighted by default. It is difficult to differentiate them from the Region of the Americas ones. What do they signify? Please revisit this to make it clear to the user what these are

**Comment by themightybruce** [comment]
I think it is very interesting to see the country range of the selected city, but agree on first viewing it may not be obvious what the highlighting means.

Perhaps when you hover over the country name we highlight or emphasize the range of country points?

So in the text below, when France is hovered over then we emphasize the range for the country.

The air in Paris, France is worse than the air in 56% of all other recorded cities.

**Comment by dominickp** [comment]
Add legend tip for selected country

**Comment by dominickp** [comment]
Add range, minimum and maximum values to X axis to better explain what the line actually is.

**Comment by dominickp** [comment]
Legend for country complete in 02c4773fd651c042d11d11ada0dd31386e0e6975

**Comment by dominickp** [comment]
Remove interaction icon complete in c7495e96b37a67330f98110285a6bc49e2bdf13b

**Comment by dominickp** [comment]
Complete range indicators in e338b6257193b51a671de0f9d88e296c54eb85f2
