### ISSUE TITLE
Display bug for small or medium sized screens

### ISSUE THREAD

**Issue by dominickp** [free-radicals/AirPollution#97]
<img width="637" alt="screen shot 2016-04-27 at 9 34 24 am" src="https://cloud.githubusercontent.com/assets/4555880/14853862/4173d440-0c5b-11e6-9a41-2789f9fc56f8.png">

**Comment by dominickp** [comment]
I don't think we're going to fix this one. Not unless we do some major changes to redraw the visualizations so they don't go outside of the containers.

**Comment by mariusdv** [comment]
I agree. removed from milestone.
